name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
            pwd
            echo "Hello World!"
      
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./environments/case.env
          
      # env.PROTOCOL == 'https'
      # env.HOST == 'example.com'
      # env.PORT == '8080'
      # env.URI == 'https://example.com:8080'