name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
            pwd
            echo "Hello World!"
      - uses: cardinalby/export-env-action@v1
        with:
          envFile: '/home/runner/work/gh-load-env-file/gh-load-env-file/constants.env'    
          expand: 'true'
      
      # env.PROTOCOL == 'https'
      # env.HOST == 'example.com'
      # env.PORT == '8080'
      # env.URI == 'https://example.com:8080'