name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: |
            pwd
            echo "Hello World!"

      - name: Load .env file
        uses: natterstefan/action-next-env@v1
        with:
            path: . # optional, default: .
            environment: development
          
      - name: Some other action
        run: |
            echo "HELLO Variable: ${{ env.FIXTURES_4 }}"
      
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: ./environments/case.env
          
      # env.PROTOCOL == 'https'
      # env.HOST == 'example.com'
      # env.PORT == '8080'
      # env.URI == 'https://example.com:8080'